# Generated by Django 6.0.5 on 2026-05-21 05:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutes', '0001_initial'),
        ('question_bank', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('practice', 'Practice'), ('quiz', 'Quiz'), ('test', 'Test'), ('assessment', 'Assessment'), ('mock_exam', 'Mock Exam'), ('final_exam', 'Final Exam')], max_length=30)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('allow_late_submit', models.BooleanField(default=False)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False)),
                ('show_result_immediately', models.BooleanField(default=False)),
                ('allow_review_after_submit', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicyear')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.cohort')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='institutes.institute')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.program')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.subject')),
            ],
            options={
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_publish_logs', to='teachers.teacherprofile')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='exams.exam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section_name', models.CharField(blank=True, max_length=150)),
                ('question_order', models.PositiveIntegerField(default=1)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('negative_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_links', to='question_bank.question')),
            ],
            options={
                'ordering': ['question_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('section_order', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('marks_per_question', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('negative_marks_per_question', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ['section_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['institute', 'academic_year'], name='exams_exam_institu_8ab9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['program', 'cohort', 'subject'], name='exams_exam_program_bed355_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'delivery_mode', 'status'], name='exams_exam_exam_ty_a2c265_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_at', 'end_at'], name='exams_exam_start_a_8ec86b_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active'], name='exams_exam_is_acti_1c1d9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_exam_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='exampublishlog',
            index=models.Index(fields=['exam', 'created_at'], name='exams_examp_exam_id_abff94_idx'),
        ),
        migrations.AddIndex(
            model_name='exampublishlog',
            index=models.Index(fields=['new_status'], name='exams_examp_new_sta_42ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'question_order'], name='exams_examq_exam_id_921086_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'question'], name='exams_examq_exam_id_238b74_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'is_active'], name='exams_examq_exam_id_5b842b_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='unique_exam_question_pair'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question_order'), name='unique_exam_question_order'),
        ),
        migrations.AddIndex(
            model_name='examsection',
            index=models.Index(fields=['exam', 'section_order'], name='exams_exams_exam_id_d7741c_idx'),
        ),
        migrations.AddIndex(
            model_name='examsection',
            index=models.Index(fields=['exam', 'is_active'], name='exams_exams_exam_id_f68237_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(fields=('exam', 'section_order'), name='unique_exam_section_order'),
        ),
    ]
