# Generated by Django 6.0.5 on 2026-05-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_assignments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examstudentassignment',
            new_name='exams_exams_exam_id_14b527_idx',
            old_name='exams_exams_exam_id_9db569_idx',
        ),
        migrations.RenameIndex(
            model_name='examstudentassignment',
            new_name='exams_exams_student_05dc5a_idx',
            old_name='exams_exams_student__2f9158_idx',
        ),
    ]
