# Generated by Django 6.0.5 on 2026-06-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_access_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exam',
            new_name='exams_exam_institu_2c5ae1_idx',
            old_name='exams_exam_institu_6ab1df_idx',
        ),
    ]
