# Generated by Django 6.0.5 on 2026-06-13 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_academics_o_namespa_845505_idx_academics_o_namespa_19c853_idx_and_more'),
        ('exams', '0007_rename_exams_exam_institu_6ab1df_idx_exams_exam_institu_2c5ae1_idx'),
        ('institutes', '0002_institute_metadata'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='source_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_owned_exams', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_type',
            field=models.CharField(choices=[('platform', 'Platform'), ('institute', 'Institute'), ('teacher', 'Teacher')], default='institute', max_length=20),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['source_type'], name='exams_exam_source__f49fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['source_teacher'], name='exams_exam_source__e4c7d6_idx'),
        ),
    ]
