# Generated by Django 6.0.5 on 2026-06-14 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_source_teacher_exam_source_type_and_more'),
        ('institutes', '0002_institute_metadata'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedExamTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audience_context', models.CharField(choices=[('institute', 'Institute'), ('teacher', 'Teacher')], default='institute', max_length=20)),
                ('blueprint', models.JSONField(blank=True, default=dict)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_exam_templates_created', to='teachers.teacherprofile')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_exam_templates', to='institutes.institute')),
            ],
            options={
                'ordering': ['name', '-updated_at'],
                'indexes': [models.Index(fields=['institute', 'audience_context'], name='exams_advan_institu_ff55f6_idx'), models.Index(fields=['created_by_teacher'], name='exams_advan_created_6901c7_idx'), models.Index(fields=['is_active'], name='exams_advan_is_acti_14ff7a_idx')],
                'constraints': [models.UniqueConstraint(fields=('institute', 'name'), name='unique_advanced_exam_template_name_per_institute')],
            },
        ),
    ]
