# Generated by Django 6.0.5 on 2026-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_academics_o_namespa_845505_idx_academics_o_namespa_19c853_idx_and_more'),
        ('exams', '0009_advancedexamtemplate'),
        ('institutes', '0002_institute_metadata'),
        ('students', '0002_studentprofile_accommodation_profile'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['institute', 'source_type', 'source_teacher'], name='exams_exam_institu_11e0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['access_key', 'access_key_enabled', 'is_active'], name='exams_exam_access__4c44de_idx'),
        ),
        migrations.AddIndex(
            model_name='examstudentassignment',
            index=models.Index(fields=['exam', 'is_active', 'student'], name='exams_exams_exam_id_90d6ec_idx'),
        ),
    ]
