# Generated by Django 6.0.5 on 2026-07-11 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_normalize_assessment_family_codes_lowercase'),
        ('exams', '0012_examsection_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAccessSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slot_label', models.CharField(max_length=100)),
                ('slot_start_at', models.DateTimeField()),
                ('slot_end_at', models.DateTimeField()),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('assignment_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('start_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_access_slots', to='academics.cohort')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_slots', to='exams.exam')),
            ],
            options={
                'ordering': ['slot_start_at', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='examstudentassignment',
            name='access_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='exams.examaccessslot'),
        ),
        migrations.AddIndex(
            model_name='examaccessslot',
            index=models.Index(fields=['exam', 'status', 'slot_start_at'], name='exams_exama_exam_id_324f18_idx'),
        ),
        migrations.AddIndex(
            model_name='examaccessslot',
            index=models.Index(fields=['exam', 'cohort', 'status'], name='exams_exama_exam_id_5cf917_idx'),
        ),
        migrations.AddIndex(
            model_name='examaccessslot',
            index=models.Index(fields=['slot_start_at', 'slot_end_at'], name='exams_exama_slot_st_050fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='examaccessslot',
            index=models.Index(fields=['status', 'is_active'], name='exams_exama_status_d72f7d_idx'),
        ),
    ]
