# Generated by Django 6.0.5 on 2026-07-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0013_examaccessslot_examstudentassignment_access_slot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="access_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("global_window_legacy", "Global Window (Legacy)"),
                    ("slot_managed", "Slot Managed"),
                    ("long_window_attempt_managed", "Long Window Attempt Managed"),
                    ("platform_event_managed", "Platform Event Managed"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
