# Generated by Django 6.0.5 on 2026-07-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_refresh_exam_economy_option_catalog'),
        ('exams', '0014_exam_access_mode'),
        ('institutes', '0006_institute_management_mode'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('total_marks__gte', 0)), name='exam_total_marks_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('passing_marks__gte', 0)), name='exam_passing_marks_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('passing_marks__lte', models.F('total_marks'))), name='exam_passing_marks_lte_total_marks'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('start_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='exam_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('result_publish_at__isnull', True), ('end_at__isnull', True), ('result_publish_at__gte', models.F('end_at')), _connector='OR'), name='exam_result_publish_not_before_end'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('review_available_until__isnull', True), ('review_available_from__isnull', True), ('review_available_until__gt', models.F('review_available_from')), _connector='OR'), name='exam_review_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'teacher'), _negated=True), ('source_teacher__isnull', False), _connector='OR'), name='exam_teacher_source_requires_teacher'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt_policy', 'unlimited_practice'), _negated=True), ('max_attempts', 1), _connector='OR'), name='exam_unlimited_practice_uses_single_attempt_counter'),
        ),
    ]
