# Generated by Django 6.0.5 on 2026-05-21 05:13

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admission_no', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(db_index=True, editable=False, max_length=220)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='students/profiles/')),
                ('address', models.TextField(blank=True)),
                ('joined_at', models.DateField(default=datetime.date.today)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.academicyear')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.cohort')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institutes.institute')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.program')),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'admission_no'],
                'indexes': [models.Index(fields=['institute', 'program', 'cohort'], name='students_st_institu_24762b_idx'), models.Index(fields=['institute', 'academic_year'], name='students_st_institu_bff1f8_idx'), models.Index(fields=['full_name'], name='students_st_full_na_2c960f_idx'), models.Index(fields=['is_active'], name='students_st_is_acti_f5bb3f_idx')],
                'constraints': [models.UniqueConstraint(fields=('institute', 'admission_no'), name='unique_student_admission_no_per_institute')],
            },
        ),
    ]
