# Generated by Django 6.0.5 on 2026-07-18 04:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


def forward_backfill_student_accommodation_profiles(apps, schema_editor):
    student_profile_model = apps.get_model("students", "StudentProfile")
    accommodation_model = apps.get_model("students", "StudentAccommodationProfile")
    database_alias = schema_editor.connection.alias

    def normalized_snapshot_from_dict(raw_profile):
        raw_profile = raw_profile if isinstance(raw_profile, dict) else {}

        def integer_value(key):
            value = raw_profile.get(key, 0)
            try:
                numeric = int(value)
            except (TypeError, ValueError):
                return 0
            return max(numeric, 0)

        def string_value(key):
            value = raw_profile.get(key, "")
            return value.strip() if isinstance(value, str) else ""

        extra_time_minutes = min(integer_value("extra_time_minutes"), 180)
        extra_time_percentage = min(integer_value("extra_time_percentage"), 300)
        additional_violation_allowance = min(integer_value("additional_violation_allowance"), 2)
        simplified_warning_copy = bool(raw_profile.get("simplified_warning_copy", False))
        alternative_instructions = string_value("alternative_instructions")
        notes = string_value("notes")

        has_accommodations = any(
            [
                extra_time_minutes > 0,
                extra_time_percentage > 0,
                additional_violation_allowance > 0,
                simplified_warning_copy,
                bool(alternative_instructions),
                bool(notes),
            ]
        )

        return {
            "extra_time_minutes": extra_time_minutes,
            "extra_time_percentage": extra_time_percentage,
            "additional_violation_allowance": additional_violation_allowance,
            "simplified_warning_copy": simplified_warning_copy,
            "alternative_instructions": alternative_instructions,
            "notes": notes,
            "source": string_value("source") or ("student_profile" if has_accommodations else "none"),
        }

    for student in student_profile_model.objects.using(database_alias).all():
        normalized = normalized_snapshot_from_dict(student.accommodation_profile)
        accommodation_model.objects.using(database_alias).update_or_create(
            student=student,
            defaults=normalized,
        )


def reverse_backfill_student_accommodation_profiles(apps, schema_editor):
    student_profile_model = apps.get_model("students", "StudentProfile")
    accommodation_model = apps.get_model("students", "StudentAccommodationProfile")
    database_alias = schema_editor.connection.alias

    for accommodation in accommodation_model.objects.using(database_alias).select_related("student"):
        student_profile_model.objects.using(database_alias).filter(
            pk=accommodation.student_id
        ).update(
            accommodation_profile={
                "extra_time_minutes": accommodation.extra_time_minutes,
                "extra_time_percentage": accommodation.extra_time_percentage,
                "additional_violation_allowance": accommodation.additional_violation_allowance,
                "simplified_warning_copy": accommodation.simplified_warning_copy,
                "alternative_instructions": accommodation.alternative_instructions,
                "notes": accommodation.notes,
                "source": accommodation.source,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_accommodation_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccommodationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_time_minutes', models.PositiveIntegerField(default=0)),
                ('extra_time_percentage', models.PositiveIntegerField(default=0)),
                ('additional_violation_allowance', models.PositiveIntegerField(default=0)),
                ('simplified_warning_copy', models.BooleanField(default=False)),
                ('alternative_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='typed_accommodation_profile', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__full_name'],
                'indexes': [models.Index(fields=['source', 'is_active'], name='students_st_source_12f629_idx')],
            },
        ),
        migrations.RunPython(
            forward_backfill_student_accommodation_profiles,
            reverse_backfill_student_accommodation_profiles,
        ),
    ]
