# Generated by Django 6.0.5 on 2026-07-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentaccommodationprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='accommodation_profile',
        ),
    ]
