# Generated by Django 6.0.5 on 2026-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='registration_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
