# Generated by Django 6.0.5 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofile_registration_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="onboarding_role",
            field=models.CharField(blank=True, choices=[("platform_admin", "Platform Admin"), ("institute_admin", "Institute Admin"), ("teacher", "Teacher"), ("student", "Student"), ("parent", "Parent")], default="", max_length=30),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="onboarding_status",
            field=models.CharField(choices=[("not_started", "Not Started"), ("in_progress", "In Progress"), ("completed", "Completed")], default="completed", max_length=20),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="onboarding_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="profile_completion_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="profile_completion_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="accountprofile",
            index=models.Index(fields=["profile_completion_required", "onboarding_status"], name="accounts_onboard_state_idx"),
        ),
    ]
