# Generated by Django 6.0.5 on 2026-06-12 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountprofile_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('signup_source', models.CharField(blank=True, max_length=50)),
                ('landing_variant', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('device_category', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('browser_family', models.CharField(blank=True, max_length=100)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=150)),
                ('utm_term', models.CharField(blank=True, max_length=150)),
                ('utm_content', models.CharField(blank=True, max_length=150)),
                ('referral_channel', models.CharField(blank=True, max_length=50)),
                ('referral_identifier', models.CharField(blank=True, max_length=150)),
                ('invite_code', models.CharField(blank=True, max_length=100)),
                ('school_name_text', models.CharField(blank=True, max_length=255)),
                ('school_normalization_status', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_profile', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['account_profile__user__username'],
                'indexes': [models.Index(fields=['signup_source', 'platform'], name='accounts_ac_signup__4ba560_idx'), models.Index(fields=['referral_channel', 'referral_identifier'], name='accounts_ac_referra_332ae2_idx'), models.Index(fields=['school_normalization_status'], name='accounts_ac_school__a628f4_idx'), models.Index(fields=['is_active'], name='accounts_ac_is_acti_f3ee00_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('detected_country', models.CharField(blank=True, max_length=100)),
                ('detected_state', models.CharField(blank=True, max_length=100)),
                ('detected_city', models.CharField(blank=True, max_length=100)),
                ('detected_pincode', models.CharField(blank=True, max_length=20)),
                ('detected_timezone', models.CharField(blank=True, max_length=100)),
                ('detection_source', models.CharField(blank=True, max_length=50)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_country', models.CharField(blank=True, max_length=100)),
                ('confirmed_state', models.CharField(blank=True, max_length=100)),
                ('confirmed_city', models.CharField(blank=True, max_length=100)),
                ('confirmed_pincode', models.CharField(blank=True, max_length=20)),
                ('confirmed_timezone', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_profile', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['account_profile__user__username'],
                'indexes': [models.Index(fields=['confirmed_country', 'confirmed_state', 'confirmed_city'], name='accounts_ac_confirm_ef208a_idx'), models.Index(fields=['detection_source'], name='accounts_ac_detecti_d71662_idx'), models.Index(fields=['is_active'], name='accounts_ac_is_acti_f7f766_idx')],
            },
        ),
    ]
