# Generated by Django 6.0.5 on 2026-06-11 08:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutes', '0002_institute_metadata'),
        ('students', '0002_studentprofile_accommodation_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_type', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('provider_order_reference', models.CharField(blank=True, max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('referrer_stars', models.PositiveIntegerField(default=0)),
                ('referee_stars', models.PositiveIntegerField(default=0)),
                ('reward_side', models.CharField(choices=[('referrer', 'Referrer'), ('referee', 'Referee'), ('both', 'Both')], default='both', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_programs', to='institutes.institute')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='institutes.institute')),
                ('owner_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='students.studentprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='economy.referralprogram')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('signup', 'Signup'), ('referral', 'Referral'), ('exam_completion', 'Exam Completion'), ('score_threshold', 'Score Threshold'), ('streak', 'Streak'), ('topic_mastery', 'Topic Mastery'), ('admin_campaign', 'Admin Campaign')], max_length=40)),
                ('stars_awarded', models.PositiveIntegerField(default=0)),
                ('score_threshold_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_count_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('streak_count_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='institutes.institute')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_rules', to='academics.subject')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StarLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20)),
                ('source_type', models.CharField(choices=[('signup_bonus', 'Signup Bonus'), ('referral_bonus', 'Referral Bonus'), ('admin_grant', 'Admin Grant'), ('exam_reward', 'Exam Reward'), ('purchase', 'Purchase'), ('subscription', 'Subscription'), ('content_spend', 'Content Spend'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('expiry', 'Expiry')], max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('stars_delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('balance_source', models.CharField(choices=[('earned', 'Earned'), ('admin_granted', 'Admin Granted'), ('paid', 'Paid'), ('subscription', 'Subscription'), ('adjustment', 'Adjustment')], default='earned', max_length=30)),
                ('effective_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_star_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_ledger_entries', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_ledger_entries', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='institutes.institute')),
                ('referee_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events_as_referee', to='students.studentprofile')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='economy.referralcode')),
                ('referrer_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events_as_referrer', to='students.studentprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='economy.referralprogram')),
                ('referee_ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_event_as_referee', to='economy.starledger')),
                ('referrer_ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_event_as_referrer', to='economy.starledger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('voided', 'Voided'), ('refunded', 'Refunded')], max_length=20)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_transaction_reference', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='institutes.institute')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='economy.paymentorder')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='economy.starledger')),
            ],
            options={
                'ordering': ['-processed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StarPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('stars_credited', models.PositiveIntegerField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_packs', to='institutes.institute')),
            ],
            options={
                'ordering': ['sort_order', 'price_amount', 'name'],
            },
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='star_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='economy.starpack'),
        ),
        migrations.CreateModel(
            name='StudentEconomyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_stars', models.IntegerField(default=0)),
                ('lifetime_earned_stars', models.PositiveIntegerField(default=0)),
                ('lifetime_spent_stars', models.PositiveIntegerField(default=0)),
                ('admin_granted_stars', models.PositiveIntegerField(default=0)),
                ('paid_credited_stars', models.PositiveIntegerField(default=0)),
                ('subscription_credited_stars', models.PositiveIntegerField(default=0)),
                ('reserved_stars', models.PositiveIntegerField(default=0)),
                ('last_ledger_entry_at', models.DateTimeField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_economy_profiles', to='institutes.institute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economy_profile', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__full_name'],
            },
        ),
        migrations.AddField(
            model_name='starledger',
            name='economy_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='economy.studenteconomyprofile'),
        ),
        migrations.CreateModel(
            name='StudentEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(max_length=50)),
                ('content_key', models.CharField(max_length=100)),
                ('content_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entitlement_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('consumed', 'Consumed')], max_length=20)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_entitlements', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entitlements', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='students.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_targets', to='academics.subject')),
            ],
            options={
                'ordering': ['student__full_name', 'entitlement_code'],
            },
        ),
        migrations.CreateModel(
            name='StudentRewardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_key', models.CharField(max_length=150)),
                ('event_reference', models.CharField(blank=True, max_length=150)),
                ('awarded_stars', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reward_events', to='institutes.institute')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_event', to='economy.starledger')),
                ('reward_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to='economy.rewardrule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-processed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subscriptions', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentUnlockState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(max_length=50)),
                ('content_key', models.CharField(max_length=100)),
                ('content_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('hidden', 'Hidden'), ('consumed', 'Consumed')], max_length=20)),
                ('lock_reason_code', models.CharField(blank=True, max_length=100)),
                ('lock_reason_message', models.TextField(blank=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_unlock_states', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_unlock_states', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_states', to='students.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_targets', to='academics.subject')),
            ],
            options={
                'ordering': ['student__full_name', 'content_type', 'content_key'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('event_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_billing_events', to='institutes.institute')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_billing_event', to='economy.starledger')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_billing_events', to='economy.paymenttransaction')),
                ('student_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='economy.studentsubscription')),
            ],
            options={
                'ordering': ['-event_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='institutes.institute')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_cycles', to='institutes.institute')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='economy.subscriptionplan')),
            ],
            options={
                'ordering': ['plan__name', 'price_amount'],
            },
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='plan_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subscriptions', to='economy.subscriptionplancycle'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='subscription_plan_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='economy.subscriptionplancycle'),
        ),
        migrations.CreateModel(
            name='SubscriptionStarCreditRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stars_credited', models.PositiveIntegerField()),
                ('credit_on_activation', models.BooleanField(default=True)),
                ('credit_on_renewal', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_star_credit_rules', to='institutes.institute')),
                ('plan_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_credit_rules', to='economy.subscriptionplancycle')),
            ],
            options={
                'ordering': ['plan_cycle__plan__name'],
            },
        ),
        migrations.CreateModel(
            name='UnlockRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(max_length=50)),
                ('content_key', models.CharField(max_length=100)),
                ('content_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule_type', models.CharField(choices=[('stars_balance', 'Stars Balance'), ('entitlement', 'Entitlement'), ('exam_completion', 'Exam Completion'), ('score_threshold', 'Score Threshold'), ('admin_approval', 'Admin Approval'), ('composite', 'Composite')], max_length=30)),
                ('required_star_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('required_entitlement_code', models.CharField(blank=True, max_length=100)),
                ('required_completion_count', models.PositiveIntegerField(blank=True, null=True)),
                ('required_score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admin_override_allowed', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_rules', to='institutes.institute')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_targets', to='academics.subject')),
            ],
            options={
                'ordering': ['priority', 'content_type', 'content_key'],
            },
        ),
        migrations.CreateModel(
            name='ContentAccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(max_length=50)),
                ('content_key', models.CharField(max_length=100)),
                ('content_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('policy_type', models.CharField(choices=[('free', 'Free'), ('stars_only', 'Stars Only'), ('entitlement_only', 'Entitlement Only'), ('stars_or_entitlement', 'Stars Or Entitlement')], max_length=30)),
                ('star_cost', models.PositiveIntegerField(default=0)),
                ('entitlement_code', models.CharField(blank=True, max_length=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_access_policies', to='institutes.institute')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_targets', to='academics.subject')),
            ],
            options={
                'ordering': ['priority', 'content_type', 'content_key'],
                'indexes': [models.Index(fields=['content_type', 'content_key'], name='economy_con_content_2fb2a2_idx'), models.Index(fields=['institute', 'policy_type'], name='economy_con_institu_8c5c65_idx'), models.Index(fields=['star_cost'], name='economy_con_star_co_a22179_idx'), models.Index(fields=['is_active'], name='economy_con_is_acti_4fc379_idx')],
                'constraints': [models.UniqueConstraint(fields=('institute', 'content_type', 'content_key', 'policy_type'), name='unique_content_access_policy_per_target_type')],
            },
        ),
        migrations.AddIndex(
            model_name='referralprogram',
            index=models.Index(fields=['institute', 'valid_from', 'valid_until'], name='economy_ref_institu_ffc214_idx'),
        ),
        migrations.AddIndex(
            model_name='referralprogram',
            index=models.Index(fields=['is_active'], name='economy_ref_is_acti_f5ec8f_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['institute', 'owner_student'], name='economy_ref_institu_dcb840_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='economy_ref_code_a25393_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['is_active'], name='economy_ref_is_acti_203282_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_referral_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['institute', 'rule_type'], name='economy_rew_institu_5d768a_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['subject', 'rule_type'], name='economy_rew_subject_d9ecad_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['valid_from', 'valid_until'], name='economy_rew_valid_f_6fb85f_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['is_active'], name='economy_rew_is_acti_5054ff_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['institute', 'referrer_student'], name='economy_ref_institu_bfb4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['institute', 'referee_student'], name='economy_ref_institu_0fa553_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralevent',
            constraint=models.UniqueConstraint(fields=('program', 'referee_student'), name='unique_referral_program_referee_student'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['institute', 'status'], name='economy_pay_institu_5f2573_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider_name', 'provider_transaction_reference'], name='economy_pay_provide_1ab8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='starpack',
            index=models.Index(fields=['institute', 'sort_order'], name='economy_sta_institu_73a524_idx'),
        ),
        migrations.AddIndex(
            model_name='starpack',
            index=models.Index(fields=['price_amount'], name='economy_sta_price_a_13b665_idx'),
        ),
        migrations.AddIndex(
            model_name='starpack',
            index=models.Index(fields=['is_active'], name='economy_sta_is_acti_372fa8_idx'),
        ),
        migrations.AddConstraint(
            model_name='starpack',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_star_pack_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='studenteconomyprofile',
            index=models.Index(fields=['institute', 'student'], name='economy_stu_institu_4482b2_idx'),
        ),
        migrations.AddIndex(
            model_name='studenteconomyprofile',
            index=models.Index(fields=['available_stars'], name='economy_stu_availab_585938_idx'),
        ),
        migrations.AddIndex(
            model_name='studenteconomyprofile',
            index=models.Index(fields=['is_active'], name='economy_stu_is_acti_e1d3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='starledger',
            index=models.Index(fields=['institute', 'student', 'effective_at'], name='economy_sta_institu_e648fd_idx'),
        ),
        migrations.AddIndex(
            model_name='starledger',
            index=models.Index(fields=['economy_profile', 'effective_at'], name='economy_sta_economy_83552d_idx'),
        ),
        migrations.AddIndex(
            model_name='starledger',
            index=models.Index(fields=['source_type', 'source_id'], name='economy_sta_source__ba16ce_idx'),
        ),
        migrations.AddIndex(
            model_name='starledger',
            index=models.Index(fields=['balance_source'], name='economy_sta_balance_d2acd9_idx'),
        ),
        migrations.AddIndex(
            model_name='studententitlement',
            index=models.Index(fields=['content_type', 'content_key'], name='economy_stu_content_482610_idx'),
        ),
        migrations.AddIndex(
            model_name='studententitlement',
            index=models.Index(fields=['institute', 'student', 'status'], name='economy_stu_institu_d38402_idx'),
        ),
        migrations.AddIndex(
            model_name='studententitlement',
            index=models.Index(fields=['entitlement_code', 'status'], name='economy_stu_entitle_2a688c_idx'),
        ),
        migrations.AddIndex(
            model_name='studententitlement',
            index=models.Index(fields=['valid_from', 'valid_until'], name='economy_stu_valid_f_400355_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrewardevent',
            index=models.Index(fields=['institute', 'student', 'processed_at'], name='economy_stu_institu_6ef3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrewardevent',
            index=models.Index(fields=['reward_rule', 'processed_at'], name='economy_stu_reward__a66441_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentrewardevent',
            constraint=models.UniqueConstraint(fields=('student', 'reward_rule', 'event_key'), name='unique_student_reward_rule_event_key'),
        ),
        migrations.AddIndex(
            model_name='studentunlockstate',
            index=models.Index(fields=['content_type', 'content_key'], name='economy_stu_content_15dc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentunlockstate',
            index=models.Index(fields=['institute', 'student', 'status'], name='economy_stu_institu_9b99d8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentunlockstate',
            index=models.Index(fields=['last_evaluated_at'], name='economy_stu_last_ev_32c8ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentunlockstate',
            constraint=models.UniqueConstraint(fields=('student', 'content_type', 'content_key'), name='unique_student_unlock_state_per_target'),
        ),
        migrations.AddIndex(
            model_name='subscriptionbillingevent',
            index=models.Index(fields=['institute', 'event_type', 'event_at'], name='economy_sub_institu_1ca956_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionbillingevent',
            index=models.Index(fields=['student_subscription', 'event_at'], name='economy_sub_student_2741d3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['institute', 'code'], name='economy_sub_institu_95367a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active'], name='economy_sub_is_acti_12f147_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_subscription_plan_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplancycle',
            index=models.Index(fields=['institute', 'billing_interval'], name='economy_sub_institu_fdf0af_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplancycle',
            index=models.Index(fields=['price_amount'], name='economy_sub_price_a_c1e30f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplancycle',
            index=models.Index(fields=['is_active'], name='economy_sub_is_acti_551724_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplancycle',
            constraint=models.UniqueConstraint(fields=('plan', 'billing_interval', 'interval_count'), name='unique_subscription_plan_cycle'),
        ),
        migrations.AddIndex(
            model_name='studentsubscription',
            index=models.Index(fields=['institute', 'student', 'status'], name='economy_stu_institu_46e125_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubscription',
            index=models.Index(fields=['current_period_start', 'current_period_end'], name='economy_stu_current_95e238_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubscription',
            index=models.Index(fields=['is_active'], name='economy_stu_is_acti_494674_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['institute', 'student', 'status'], name='economy_pay_institu_762540_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['provider_name', 'provider_order_reference'], name='economy_pay_provide_7878f4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['is_active'], name='economy_pay_is_acti_e0c8da_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionstarcreditrule',
            index=models.Index(fields=['institute', 'stars_credited'], name='economy_sub_institu_e8d6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionstarcreditrule',
            index=models.Index(fields=['is_active'], name='economy_sub_is_acti_c682c0_idx'),
        ),
        migrations.AddIndex(
            model_name='unlockrule',
            index=models.Index(fields=['content_type', 'content_key'], name='economy_unl_content_94bbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='unlockrule',
            index=models.Index(fields=['institute', 'rule_type'], name='economy_unl_institu_189ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='unlockrule',
            index=models.Index(fields=['priority'], name='economy_unl_priorit_e0a1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='unlockrule',
            index=models.Index(fields=['is_active'], name='economy_unl_is_acti_d841b6_idx'),
        ),
    ]
