# Generated by Django 6.0.5 on 2026-06-27 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_refresh_assessment_family_contracts'),
        ('economy', '0002_economyoperatorpolicyconfig'),
        ('institutes', '0002_institute_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('package_type', models.CharField(choices=[('subject_library', 'Subject Library'), ('topic_bundle', 'Topic Bundle'), ('exam_family_bundle', 'Exam Family Bundle'), ('custom_bundle', 'Custom Bundle'), ('feature_bundle', 'Feature Bundle')], max_length=40)),
                ('ownership_type', models.CharField(choices=[('platform', 'Platform'), ('institute', 'Institute')], default='platform', max_length=20)),
                ('access_mode', models.CharField(choices=[('full_scope', 'Full Scope'), ('quota_limited', 'Quota Limited'), ('link_on_demand', 'Link On Demand'), ('materialize_on_entitlement', 'Materialize On Entitlement')], default='full_scope', max_length=40)),
                ('is_public_catalog', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_packages', to='institutes.institute')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankPackageScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_source_type', models.CharField(default='platform_only', max_length=30)),
                ('difficulty_level', models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('question_type', models.CharField(blank=True, choices=[('mcq_single', 'MCQ Single'), ('mcq_multiple', 'MCQ Multiple'), ('true_false', 'True / False'), ('assertion_reason', 'Assertion / Reason'), ('matrix_match', 'Matrix Match'), ('short_answer', 'Short Answer'), ('fill_in_blanks', 'Fill in the Blanks'), ('numeric_answer', 'Numeric Answer'), ('essay_manual_review', 'Essay Manual Review')], max_length=30)),
                ('master_visibility', models.CharField(blank=True, choices=[('private', 'Private'), ('shared_by_request', 'Shared By Request'), ('public', 'Public')], max_length=30)),
                ('max_questions_total', models.PositiveIntegerField(blank=True, null=True)),
                ('max_questions_per_topic', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_package_scopes', to='institutes.institute')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='economy.questionbankpackage')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_package_scopes', to='academics.program')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_package_scopes', to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_package_scopes', to='academics.topic')),
            ],
            options={
                'ordering': ['package__sort_order', 'subject__name', 'topic__name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanQuestionBankPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grant_mode', models.CharField(choices=[('included', 'Included'), ('optional_addon', 'Optional Addon'), ('trial', 'Trial')], default='included', max_length=30)),
                ('is_default', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_question_bank_packages', to='institutes.institute')),
                ('question_bank_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_links', to='economy.questionbankpackage')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_package_links', to='economy.subscriptionplan')),
            ],
            options={
                'ordering': ['subscription_plan__name', 'question_bank_package__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='questionbankpackage',
            index=models.Index(fields=['institute', 'code'], name='economy_que_institu_3a5569_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankpackage',
            index=models.Index(fields=['institute', 'package_type'], name='economy_que_institu_7eced8_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankpackage',
            index=models.Index(fields=['is_public_catalog', 'is_active'], name='economy_que_is_publ_e056f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbankpackage',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_question_bank_package_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='questionbankpackagescope',
            index=models.Index(fields=['package', 'is_active'], name='economy_que_package_019d68_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankpackagescope',
            index=models.Index(fields=['institute', 'subject', 'topic'], name='economy_que_institu_98cacd_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankpackagescope',
            index=models.Index(fields=['institute', 'question_source_type'], name='economy_que_institu_1d20d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbankpackagescope',
            constraint=models.UniqueConstraint(fields=('package', 'program', 'subject', 'topic', 'difficulty_level', 'question_type', 'master_visibility'), name='unique_question_bank_package_scope_row'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplanquestionbankpackage',
            index=models.Index(fields=['institute', 'subscription_plan'], name='economy_sub_institu_dd484a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplanquestionbankpackage',
            index=models.Index(fields=['institute', 'question_bank_package'], name='economy_sub_institu_06fa51_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplanquestionbankpackage',
            index=models.Index(fields=['grant_mode', 'is_active'], name='economy_sub_grant_m_cd114b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplanquestionbankpackage',
            constraint=models.UniqueConstraint(fields=('subscription_plan', 'question_bank_package'), name='unique_subscription_plan_question_bank_package'),
        ),
    ]
