# Generated by Django 6.0.5 on 2026-06-27 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_questionbankpackage_questionbankpackagescope_and_more'),
        ('institutes', '0002_institute_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteQuestionEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='draft', max_length=20)),
                ('granted_via', models.CharField(choices=[('subscription', 'Subscription'), ('admin_grant', 'Admin Grant'), ('trial', 'Trial'), ('migration', 'Migration')], default='admin_grant', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_question_bank_entitlements', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_entitlements', to='institutes.institute')),
                ('question_bank_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_entitlements', to='economy.questionbankpackage')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_question_bank_entitlements', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_entitlements', to='economy.subscriptionplan')),
                ('subscription_plan_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_entitlements', to='economy.subscriptionplancycle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institute', 'status'], name='economy_ins_institu_48f689_idx'), models.Index(fields=['question_bank_package', 'status'], name='economy_ins_questio_9857fe_idx'), models.Index(fields=['subscription_plan', 'status'], name='economy_ins_subscri_fd1e8b_idx'), models.Index(fields=['starts_at', 'ends_at'], name='economy_ins_starts__c8aa97_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'active', 'paused'])), fields=('institute', 'question_bank_package'), name='unique_live_institute_question_bank_entitlement')],
            },
        ),
        migrations.CreateModel(
            name='InstituteQuestionFeatureEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feature_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_feature_entitlements', to='institutes.institute')),
                ('source_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_entitlements', to='economy.questionbankpackage')),
                ('source_subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_entitlements', to='economy.subscriptionplan')),
            ],
            options={
                'ordering': ['feature_code', '-created_at'],
                'indexes': [models.Index(fields=['institute', 'feature_code', 'status'], name='economy_ins_institu_dce37c_idx'), models.Index(fields=['source_package', 'status'], name='economy_ins_source__9c53b2_idx'), models.Index(fields=['starts_at', 'ends_at'], name='economy_ins_starts__48c1df_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'active', 'paused'])), fields=('institute', 'feature_code'), name='unique_live_institute_question_feature_entitlement')],
            },
        ),
    ]
