# Generated by Django 6.0.5 on 2026-06-27 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_institutequestionentitlement_and_more'),
        ('exams', '0012_examsection_subject'),
        ('institutes', '0002_institute_metadata'),
        ('question_bank', '0011_expand_question_type_choices_matrix_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteQuestionUsageLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('question_linked', 'Question Linked'), ('question_materialized', 'Question Materialized'), ('exam_created', 'Exam Created'), ('exam_published', 'Exam Published'), ('question_unlinked', 'Question Unlinked'), ('entitlement_override', 'Entitlement Override')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('effective_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_entries', to='economy.institutequestionentitlement')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_usage_entries', to='exams.exam')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_usage_entries', to='institutes.institute')),
                ('master_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_usage_entries', to='question_bank.masterquestion')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_question_bank_usage_entries', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_usage_entries', to='question_bank.question')),
                ('question_bank_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='economy.questionbankpackage')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
                'indexes': [models.Index(fields=['institute', 'action_type'], name='economy_ins_institu_b5e8e6_idx'), models.Index(fields=['question_bank_package', 'action_type'], name='economy_ins_questio_7db3bd_idx'), models.Index(fields=['entitlement', 'action_type'], name='economy_ins_entitle_7551fb_idx'), models.Index(fields=['effective_at'], name='economy_ins_effecti_cdb6fc_idx')],
            },
        ),
    ]
