# Generated by Django 6.0.5 on 2026-06-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_institutesubscriptionrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='institutesubscriptionrequest',
            new_name='economy_ins_institu_c36d9c_idx',
            old_name='economy_ins_institu_0d9ce7_idx',
        ),
        migrations.RenameIndex(
            model_name='institutesubscriptionrequest',
            new_name='economy_ins_subscri_c803cc_idx',
            old_name='economy_ins_subscri_521fb8_idx',
        ),
        migrations.RenameIndex(
            model_name='institutesubscriptionrequest',
            new_name='economy_ins_is_acti_f5e1af_idx',
            old_name='economy_ins_is_acti_90f9d3_idx',
        ),
    ]
