# Generated by Django 6.0.5 on 2026-07-11 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0011_studentexamattempt_access_slot_and_more'),
        ('economy', '0007_rename_economy_ins_institu_0d9ce7_idx_economy_ins_institu_c36d9c_idx_and_more'),
        ('exams', '0013_examaccessslot_examstudentassignment_access_slot_and_more'),
        ('institutes', '0005_rename_institutes__institu_1eb390_idx_institutes__institu_749c8d_idx_and_more'),
        ('students', '0002_studentprofile_accommodation_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscriptionAllowanceUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_period_start', models.DateTimeField()),
                ('billing_period_end', models.DateTimeField()),
                ('consumed_count', models.PositiveIntegerField(default=1)),
                ('consumed_at', models.DateTimeField()),
                ('consumption_reason', models.CharField(default='attempt_start', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_allowance_usage_entry', to='attempts.studentexamattempt')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_allowance_usage_entries', to='exams.exam')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subscription_allowance_usage_entries', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_allowance_usage_entries', to='students.studentprofile')),
                ('student_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_usage_entries', to='economy.studentsubscription')),
            ],
            options={
                'ordering': ['-consumed_at', '-created_at'],
                'indexes': [models.Index(fields=['student_subscription', 'consumed_at'], name='economy_stu_student_2ab1ef_idx'), models.Index(fields=['student', 'billing_period_start', 'billing_period_end'], name='economy_stu_student_30702f_idx'), models.Index(fields=['institute', 'consumption_reason'], name='economy_stu_institu_79b2cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanExamAllowanceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('included_exam_attempts', models.PositiveIntegerField(default=1)),
                ('allowance_period_mode', models.CharField(choices=[('billing_cycle', 'Billing Cycle')], default='billing_cycle', max_length=30)),
                ('counting_scope', models.CharField(choices=[('all_eligible_exams', 'All Eligible Exams')], default='all_eligible_exams', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan_exam_allowance_configs', to='institutes.institute')),
                ('plan_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_allowance_config', to='economy.subscriptionplancycle')),
            ],
            options={
                'ordering': ['plan_cycle__plan__name', 'plan_cycle__price_amount', 'created_at'],
                'indexes': [models.Index(fields=['institute', 'plan_cycle'], name='economy_sub_institu_2a9bde_idx'), models.Index(fields=['allowance_period_mode', 'is_active'], name='economy_sub_allowan_606235_idx')],
            },
        ),
    ]
