# Generated by Django 6.0.5 on 2026-07-18 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


def forward_backfill_grant_modes(apps, schema_editor):
    request_model = apps.get_model("economy", "InstituteSubscriptionRequest")
    grant_mode_model = apps.get_model("economy", "InstituteSubscriptionRequestGrantMode")
    database_alias = schema_editor.connection.alias

    for request in request_model.objects.using(database_alias).all():
        normalized_modes = [
            str(mode).strip()
            for mode in (request.grant_modes or [])
            if str(mode).strip()
        ]
        for index, mode in enumerate(normalized_modes):
            grant_mode_model.objects.using(database_alias).update_or_create(
                subscription_request=request,
                grant_mode=mode,
                defaults={"sort_order": index},
            )


def reverse_backfill_grant_modes(apps, schema_editor):
    request_model = apps.get_model("economy", "InstituteSubscriptionRequest")
    grant_mode_model = apps.get_model("economy", "InstituteSubscriptionRequestGrantMode")
    database_alias = schema_editor.connection.alias

    for request in request_model.objects.using(database_alias).all():
        normalized_modes = list(
            grant_mode_model.objects.using(database_alias)
            .filter(subscription_request=request)
            .order_by("sort_order", "created_at")
            .values_list("grant_mode", flat=True)
        )
        request_model.objects.using(database_alias).filter(pk=request.pk).update(
            grant_modes=normalized_modes
        )


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0008_studentsubscriptionallowanceusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteSubscriptionRequestGrantMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grant_mode', models.CharField(choices=[('included', 'Included'), ('optional_addon', 'Optional Addon'), ('trial', 'Trial')], max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('subscription_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_mode_links', to='economy.institutesubscriptionrequest')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['subscription_request', 'sort_order'], name='economy_ins_subscri_9a31cc_idx'), models.Index(fields=['grant_mode', 'is_active'], name='economy_ins_grant_m_a4fdb9_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscription_request', 'grant_mode'), name='unique_subscription_request_grant_mode'), models.UniqueConstraint(fields=('subscription_request', 'sort_order'), name='unique_subscription_request_grant_mode_order')],
            },
        ),
        migrations.RunPython(forward_backfill_grant_modes, reverse_backfill_grant_modes),
    ]
