from django.urls import path

from apps.accounts.views import (
    LoginView,
    MeView,
    OnboardingProfileView,
    PublicRegisterView,
    PublicRegistrationOptionsView,
    RefreshSessionView,
    StudentAttemptListView,
    StudentAvailableExamView,
    StudentExamAccessKeyResolveView,
    StudentExamDetailView,
    StudentInsightSummaryView,
    StudentQuestionAnalyticsView,
    StudentResultListView,
    InstituteDashboardSummaryView,
    TeacherExamListView,
    TeacherInsightSummaryView,
    TeacherQuestionListView,
    TeacherQuestionPerformanceView,
    TeacherResultSummaryView,
)

app_name = "accounts"
urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/register/", PublicRegisterView.as_view(), name="register"),
    path("auth/register/options/", PublicRegistrationOptionsView.as_view(), name="register-options"),
    path("auth/refresh/", RefreshSessionView.as_view(), name="refresh"),
    path("auth/me/", MeView.as_view(), name="me"),
    path("onboarding/profile/", OnboardingProfileView.as_view(), name="onboarding-profile"),
    path("student/exams/available/", StudentAvailableExamView.as_view(), name="student-available-exams"),
    path("student/exams/resolve-key/", StudentExamAccessKeyResolveView.as_view(), name="student-exam-resolve-key"),
    path("student/exams/<uuid:exam_id>/detail/", StudentExamDetailView.as_view(), name="student-exam-detail"),
    path("student/results/", StudentResultListView.as_view(), name="student-results"),
    path("student/insights/summary/", StudentInsightSummaryView.as_view(), name="student-insights-summary"),
    path("student/insights/question-analytics/", StudentQuestionAnalyticsView.as_view(), name="student-question-analytics"),
    path("student/attempts/", StudentAttemptListView.as_view(), name="student-attempts"),
    path("institute/dashboard/summary/", InstituteDashboardSummaryView.as_view(), name="institute-dashboard-summary"),
    path("teacher/exams/", TeacherExamListView.as_view(), name="teacher-exams"),
    path("teacher/questions/", TeacherQuestionListView.as_view(), name="teacher-questions"),
    path("teacher/questions/performance/", TeacherQuestionPerformanceView.as_view(), name="teacher-question-performance"),
    path("teacher/results/summary/", TeacherResultSummaryView.as_view(), name="teacher-results-summary"),
    path("teacher/insights/summary/", TeacherInsightSummaryView.as_view(), name="teacher-insights-summary"),
]
