# Generated by Django 6.0.5 on 2026-05-21 05:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('institutes', '0001_initial'),
        ('question_bank', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attempt_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
                ('skipped_questions', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('negative_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('final_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('is_auto_submitted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('answer_text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('negative_marks_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='question_bank.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='question_bank.questionoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.studentexamattempt')),
            ],
            options={
                'ordering': ['question__id', '-answered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['institute', 'exam', 'student'], name='attempts_st_institu_582497_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['status', 'is_active'], name='attempts_st_status_ec2428_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['started_at', 'submitted_at'], name='attempts_st_started_0098c7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['final_score', 'percentage'], name='attempts_st_final_s_2112e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'attempt_no'), name='unique_exam_student_attempt_number'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question'], name='attempts_st_attempt_0bde60_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'is_active'], name='attempts_st_attempt_53f3a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer'),
        ),
    ]
