# Generated by Django 6.0.5 on 2026-06-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_attemptintegrityevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attemptintegrityevent',
            new_name='attempts_at_attempt_b6fe2c_idx',
            old_name='attempts_at_attempt_7eb4b8_idx',
        ),
        migrations.RenameIndex(
            model_name='attemptintegrityevent',
            new_name='attempts_at_exam_id_d6e4b5_idx',
            old_name='attempts_at_exam_id_6faed8_idx',
        ),
        migrations.RenameIndex(
            model_name='attemptintegrityevent',
            new_name='attempts_at_severit_a8cb70_idx',
            old_name='attempts_at_severit_319c1c_idx',
        ),
    ]
