# Generated by Django 6.0.5 on 2026-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_rename_attempts_at_attempt_7eb4b8_idx_attempts_at_attempt_b6fe2c_idx_and_more'),
        ('exams', '0009_advancedexamtemplate'),
        ('institutes', '0002_institute_metadata'),
        ('question_bank', '0003_masterquestionattachment_masterquestionoption_and_more'),
        ('students', '0002_studentprofile_accommodation_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attemptintegrityevent',
            index=models.Index(fields=['attempt', 'counts_as_violation', 'event_at'], name='attempts_at_attempt_a097c0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question', 'is_active', 'answered_at', 'created_at'], name='attempts_st_questio_9f3ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['exam', 'status', 'is_active'], name='attempts_st_exam_id_8d9bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['student', 'is_active', 'started_at'], name='attempts_st_student_b8a483_idx'),
        ),
    ]
