# Generated by Django 6.0.5 on 2026-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_attemptintegrityevent_attempts_at_attempt_a097c0_idx_and_more'),
        ('exams', '0009_advancedexamtemplate'),
        ('institutes', '0002_institute_metadata'),
        ('students', '0002_studentprofile_accommodation_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['exam', 'student', 'status', 'is_active', 'attempt_no', 'created_at'], name='attempts_st_exam_id_19b8a7_idx'),
        ),
    ]
