# Generated by Django 6.0.5 on 2026-07-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0009_studentanswer_response_artifacts_and_transcript'),
        ('exams', '0012_examsection_subject'),
        ('institutes', '0005_rename_institutes__institu_1eb390_idx_institutes__institu_749c8d_idx_and_more'),
        ('question_bank', '0011_expand_question_type_choices_matrix_match'),
        ('students', '0002_studentprofile_accommodation_profile'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'is_active', 'answered_at', 'created_at'], name='attempts_st_attempt_3eca8b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question', 'attempt', 'is_active'], name='attempts_st_questio_41d8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['student', 'status', 'is_active', 'started_at'], name='attempts_st_student_1d2d51_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['status', 'expires_at'], name='attempts_st_status_f56f1f_idx'),
        ),
    ]
