# Generated by Django 6.0.5 on 2026-07-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0010_studentanswer_attempts_st_attempt_3eca8b_idx_and_more'),
        ('exams', '0013_examaccessslot_examstudentassignment_access_slot_and_more'),
        ('institutes', '0005_rename_institutes__institu_1eb390_idx_institutes__institu_749c8d_idx_and_more'),
        ('students', '0002_studentprofile_accommodation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='access_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='exams.examaccessslot'),
        ),
        migrations.AddIndex(
            model_name='studentexamattempt',
            index=models.Index(fields=['access_slot', 'status', 'is_active'], name='attempts_st_access__7c6755_idx'),
        ),
    ]
