# Generated by Django 6.0.5 on 2026-07-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0011_studentexamattempt_access_slot_and_more'),
        ('exams', '0014_exam_access_mode'),
        ('institutes', '0006_institute_management_mode'),
        ('students', '0002_studentprofile_accommodation_profile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('submitted_at__isnull', True), ('submitted_at__gte', models.F('started_at')), _connector='OR'), name='attempt_submitted_not_before_started'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gte', models.F('started_at')), _connector='OR'), name='attempt_expires_not_before_started'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempted_questions__lte', models.F('total_questions'))), name='attempt_attempted_lte_total_questions'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answers__lte', models.F('attempted_questions'))), name='attempt_correct_lte_attempted_questions'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('incorrect_answers__lte', models.F('attempted_questions'))), name='attempt_incorrect_lte_attempted_questions'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('skipped_questions__lte', models.F('total_questions'))), name='attempt_skipped_lte_total_questions'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='attempt_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentexamattempt',
            constraint=models.CheckConstraint(condition=models.Q(('negative_score__gte', 0)), name='attempt_negative_score_non_negative'),
        ),
    ]
