# Generated by Django 6.0.5 on 2026-07-18 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


def forward_backfill_selected_options(apps, schema_editor):
    answer_model = apps.get_model("attempts", "StudentAnswer")
    link_model = apps.get_model("attempts", "StudentAnswerSelectedOption")
    database_alias = schema_editor.connection.alias

    for answer in answer_model.objects.using(database_alias).all():
        normalized_ids = [
            str(option_id).strip()
            for option_id in (answer.selected_option_ids or [])
            if str(option_id).strip()
        ]
        for index, option_id in enumerate(normalized_ids):
            link_model.objects.using(database_alias).update_or_create(
                student_answer=answer,
                question_option_id=option_id,
                defaults={"selected_order": index},
            )


def reverse_backfill_selected_options(apps, schema_editor):
    answer_model = apps.get_model("attempts", "StudentAnswer")
    link_model = apps.get_model("attempts", "StudentAnswerSelectedOption")
    database_alias = schema_editor.connection.alias

    for answer in answer_model.objects.using(database_alias).all():
        normalized_ids = list(
            link_model.objects.using(database_alias)
            .filter(student_answer=answer)
            .order_by("selected_order", "created_at")
            .values_list("question_option_id", flat=True)
        )
        answer_model.objects.using(database_alias).filter(pk=answer.pk).update(
            selected_option_ids=[str(option_id) for option_id in normalized_ids]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0012_studentexamattempt_attempt_submitted_not_before_started_and_more'),
        ('question_bank', '0011_expand_question_type_choices_matrix_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswerSelectedOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('selected_order', models.PositiveIntegerField(default=0)),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer_links', to='question_bank.questionoption')),
                ('student_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_option_links', to='attempts.studentanswer')),
            ],
            options={
                'ordering': ['selected_order', 'created_at'],
                'indexes': [models.Index(fields=['student_answer', 'selected_order'], name='attempts_st_student_50ad48_idx'), models.Index(fields=['question_option', 'is_active'], name='attempts_st_questio_84602e_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_answer', 'question_option'), name='unique_student_answer_selected_option'), models.UniqueConstraint(fields=('student_answer', 'selected_order'), name='unique_student_answer_selected_option_order')],
            },
        ),
        migrations.RunPython(
            forward_backfill_selected_options,
            reverse_backfill_selected_options,
        ),
    ]
