# Generated by Django 6.0.5 on 2026-07-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0013_studentanswerselectedoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_option_ids',
        ),
    ]
