# Generated by Django 6.0.5 on 2026-06-11 17:17

import apps.parents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_accountprofile_registration_context'),
        ('institutes', '0002_institute_metadata'),
        ('students', '0002_studentprofile_accommodation_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(db_index=True, editable=False, max_length=220)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_language', models.CharField(default='en', max_length=50)),
                ('notification_preferences', models.JSONField(blank=True, default=apps.parents.models.default_notification_preferences)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='accounts.accountprofile')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profiles', to='institutes.institute')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentChildRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('relationship_type', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('sibling_guardian', 'Sibling Guardian'), ('other', 'Other')], default='guardian', max_length=40)),
                ('relationship_label', models.CharField(blank=True, max_length=100)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('can_view_progress', models.BooleanField(default=True)),
                ('can_view_results', models.BooleanField(default=True)),
                ('can_view_wallet', models.BooleanField(default=False)),
                ('can_receive_alerts', models.BooleanField(default=True)),
                ('can_receive_weekly_summary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_parent_relationships', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_child_relationships', to='institutes.institute')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parent_relationships', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_parent_relationships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='students.studentprofile')),
                ('parent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='parents.parentprofile')),
            ],
            options={
                'ordering': ['parent_profile__full_name', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('score_drop', 'Score Drop'), ('inactivity', 'Inactivity'), ('milestone', 'Milestone'), ('result_published', 'Result Published'), ('exam_risk', 'Exam Risk')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_alerts', to='institutes.institute')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_alerts', to='students.studentprofile')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='parents.parentchildrelationship')),
                ('parent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parents.parentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['institute', 'full_name'], name='parents_par_institu_f62895_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['is_active'], name='parents_par_is_acti_3d875d_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelationship',
            index=models.Index(fields=['institute', 'parent_profile'], name='parents_par_institu_dac7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelationship',
            index=models.Index(fields=['institute', 'student'], name='parents_par_institu_51cb02_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelationship',
            index=models.Index(fields=['status', 'is_active'], name='parents_par_status_9937f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelationship',
            constraint=models.UniqueConstraint(fields=('parent_profile', 'student', 'relationship_type'), name='unique_parent_student_relationship_type'),
        ),
        migrations.AddIndex(
            model_name='parentalert',
            index=models.Index(fields=['parent_profile', 'status'], name='parents_par_parent__72ff0b_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalert',
            index=models.Index(fields=['student', 'alert_type'], name='parents_par_student_ab755a_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalert',
            index=models.Index(fields=['severity', 'created_at'], name='parents_par_severit_afd105_idx'),
        ),
    ]
