# Generated by Django 6.0.5 on 2026-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_metadata'),
        ('parents', '0001_initial'),
        ('students', '0002_studentprofile_accommodation_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parentalert',
            index=models.Index(fields=['parent_profile', 'is_active', 'created_at'], name='parents_par_parent__f251b8_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalert',
            index=models.Index(fields=['parent_profile', 'is_active', 'status', 'created_at'], name='parents_par_parent__6d27c4_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalert',
            index=models.Index(fields=['parent_profile', 'is_active', 'severity', 'created_at'], name='parents_par_parent__018823_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalert',
            index=models.Index(fields=['parent_profile', 'is_active', 'alert_type', 'created_at'], name='parents_par_parent__1c8ed6_idx'),
        ),
    ]
