import { Platform, StyleSheet } from "react-native";
import { colors, radius, spacing } from "@/theme/tokens";

const heroShadow = Platform.select({
  web: {
    boxShadow: "0px 10px 22px rgba(42, 55, 85, 0.10)",
  },
  default: {
    shadowColor: "#2a3755",
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
});

const sectionShadow = Platform.select({
  web: {
    boxShadow: "0px 4px 14px rgba(42, 55, 85, 0.06)",
  },
  default: {
    shadowColor: "#2a3755",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
});

const primaryButtonShadow = Platform.select({
  web: {
    boxShadow: "0px 8px 14px rgba(20, 86, 204, 0.20)",
  },
  default: {
    shadowColor: "#1456cc",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
});

const formCardShadow = Platform.select({
  web: {
    boxShadow: "0px 6px 18px rgba(42, 55, 85, 0.08)",
  },
  default: {
    shadowColor: "#2a3755",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
});

export const appStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bgCanvas,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFill,
    pointerEvents: "none",
  },
  backgroundWashTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: colors.bgCanvasTint,
  },
  backgroundWashBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 180,
    backgroundColor: colors.bgSurface,
    opacity: 0.55,
  },
  scrollContent: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxl,
    gap: spacing.md,
  },
  pageStack: {
    gap: spacing.md,
  },
  heroCard: {
    backgroundColor: colors.bgSurface,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderLeftWidth: 4,
    borderLeftColor: colors.bgPrimary,
    padding: spacing.lg,
    gap: spacing.sm,
    ...heroShadow,
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  eyebrow: {
    alignSelf: "flex-start",
    backgroundColor: colors.bgAccentSoft,
    color: colors.accent,
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: colors.bgWarmSoft,
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
  },
  heroBadgeText: {
    color: colors.warning,
    fontSize: 12,
    fontWeight: "700",
  },
  title: {
    color: colors.textPrimary,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: 0,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "800",
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  body: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  helper: {
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: 16,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  rowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  buttonIcon: {
    marginTop: 1,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  column: {
    gap: spacing.sm,
  },
  sectionCard: {
    backgroundColor: colors.bgSurface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    padding: spacing.md,
    gap: spacing.sm,
    ...sectionShadow,
  },
  cardHeader: {
    gap: spacing.xs,
    flexShrink: 1,
    minWidth: 0,
  },
  cardHeaderCompact: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  metricCard: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: colors.bgSurface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.sm,
    gap: spacing.xs,
    minHeight: 104,
  },
  metricCardSoft: {
    backgroundColor: colors.bgAccentSoft,
    borderColor: "#cce9e2",
  },
  skeletonBlock: {
    backgroundColor: "#e8eef7",
    borderRadius: radius.sm,
    opacity: 0.92,
  },
  skeletonBlockSoft: {
    backgroundColor: "#f0f4fa",
  },
  skeletonMetricValue: {
    width: "58%",
    height: 28,
  },
  skeletonMetricLabel: {
    width: "66%",
    height: 13,
  },
  skeletonMetricHelper: {
    width: "92%",
    height: 12,
  },
  skeletonListBody: {
    gap: spacing.sm,
  },
  skeletonListActions: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: 0,
  },
  metricLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  chip: {
    alignSelf: "flex-start",
    flexShrink: 0,
    backgroundColor: colors.bgSurfaceSoft,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  chipPrimary: {
    backgroundColor: colors.bgPrimarySoft,
    borderColor: "#cfe0ff",
  },
  chipWarm: {
    backgroundColor: colors.bgWarmSoft,
    borderColor: "#f2dfb9",
  },
  chipSuccess: {
    backgroundColor: colors.bgSuccessSoft,
    borderColor: "#cfead7",
  },
  chipDanger: {
    backgroundColor: colors.bgDangerSoft,
    borderColor: "#f3d0ca",
  },
  chipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  chipTextPrimary: {
    color: colors.bgPrimary,
  },
  chipTextWarm: {
    color: colors.warning,
  },
  chipTextSuccess: {
    color: colors.success,
  },
  chipTextDanger: {
    color: colors.danger,
  },
  primaryButton: {
    minHeight: 46,
    backgroundColor: colors.bgPrimary,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    maxWidth: "100%",
    ...primaryButtonShadow,
  },
  secondaryButton: {
    minHeight: 46,
    backgroundColor: colors.bgSurfaceSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    maxWidth: "100%",
  },
  primaryButtonText: {
    color: colors.textOnPrimary,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  secondaryButtonText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  input: {
    minHeight: 52,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.bgSurface,
    paddingHorizontal: spacing.md,
    color: colors.textPrimary,
    fontSize: 14,
  },
  inputError: {
    borderColor: "#efb4aa",
    backgroundColor: colors.bgDangerSoft,
  },
  fieldStack: {
    gap: spacing.xs,
  },
  fieldHint: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  fieldError: {
    color: colors.danger,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  formCard: {
    backgroundColor: colors.bgSurface,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    padding: spacing.xl,
    gap: spacing.md,
    ...formCardShadow,
  },
  formGrid: {
    gap: spacing.md,
  },
  formSection: {
    gap: spacing.md,
    paddingTop: spacing.sm,
  },
  formSectionHeader: {
    gap: 4,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0,
    flexShrink: 1,
  },
  listItem: {
    backgroundColor: colors.bgSurface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.md,
    gap: spacing.xs,
  },
  listItemSoft: {
    backgroundColor: colors.bgSurfaceSoft,
  },
  productCard: {
    backgroundColor: colors.bgSurface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    padding: spacing.md,
    gap: spacing.sm,
  },
  optionCard: {
    backgroundColor: colors.bgSurface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.md,
    gap: spacing.sm,
  },
  optionCardSelected: {
    backgroundColor: colors.bgPrimarySoft,
    borderColor: "#bfd4ff",
    borderLeftWidth: 4,
    borderLeftColor: colors.bgPrimary,
  },
  optionCardError: {
    borderColor: "#efb4aa",
    backgroundColor: colors.bgDangerSoft,
  },
  optionCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  optionStateText: {
    color: colors.bgPrimary,
    fontSize: 12,
    fontWeight: "800",
  },
  optionMeta: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  questionStem: {
    color: colors.textPrimary,
    fontSize: 18,
    lineHeight: 27,
    fontWeight: "700",
  },
  runtimeStatusStrip: {
    backgroundColor: colors.bgSurfaceSoft,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.md,
    gap: spacing.sm,
  },
  runtimeStatusGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  runtimeStatusItem: {
    flexBasis: "30%",
    flexGrow: 1,
    minHeight: 66,
    borderRadius: radius.md,
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.sm,
    gap: 2,
  },
  runtimeStatusValue: {
    color: colors.textPrimary,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "800",
  },
  progressTrack: {
    height: 8,
    borderRadius: radius.full,
    backgroundColor: colors.borderSoft,
    flexDirection: "row",
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: colors.bgPrimary,
  },
  navButtonPill: {
    minHeight: 36,
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
  },
  mutedPanel: {
    backgroundColor: colors.bgSurfaceSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.md,
    gap: spacing.xs,
  },
  emphasisPanel: {
    backgroundColor: colors.bgPrimarySoft,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "#cfe0ff",
    padding: spacing.md,
    gap: spacing.xs,
  },
  successPanel: {
    backgroundColor: colors.bgSuccessSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "#cfead7",
    padding: spacing.md,
    gap: spacing.xs,
  },
  errorPanel: {
    backgroundColor: colors.bgDangerSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "#f3d0ca",
    padding: spacing.md,
    gap: spacing.xs,
  },
  separator: {
    height: 1,
    backgroundColor: colors.borderSoft,
  },
  errorText: {
    color: colors.danger,
    fontSize: 13,
    lineHeight: 18,
  },
  successText: {
    color: colors.success,
    fontSize: 13,
    lineHeight: 18,
  },
  warningText: {
    color: colors.warning,
    fontSize: 13,
    lineHeight: 18,
  },
  mutedTextBlock: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
});
