# Generated by Django 6.0.5 on 2026-06-13 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order', 'name'], name='geography_c_sort_or_7298a3_idx'), models.Index(fields=['is_active'], name='geography_c_is_acti_3285a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_country_code'), models.UniqueConstraint(fields=('name',), name='unique_country_name')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='geography.country')),
            ],
            options={
                'ordering': ['country__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.state')),
            ],
            options={
                'ordering': ['state__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='geography.city')),
            ],
            options={
                'ordering': ['city__sort_order', 'sort_order', 'code'],
                'indexes': [models.Index(fields=['city', 'sort_order', 'code'], name='geography_p_city_id_e9738d_idx'), models.Index(fields=['code'], name='geography_p_code_3e5ae4_idx'), models.Index(fields=['is_active'], name='geography_p_is_acti_cc1565_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'code'), name='unique_postal_code_per_city')],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'sort_order', 'name'], name='geography_s_country_cae2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['is_active'], name='geography_s_is_acti_00e640_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'code'), name='unique_state_code_per_country'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique_state_name_per_country'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'sort_order', 'name'], name='geography_c_state_i_65bcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='geography_c_is_acti_ed0322_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_city_name_per_state'),
        ),
    ]
