# Generated by Django 6.0.5 on 2026-05-21 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='institutes.institute')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutes.institute')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='academics.academicyear')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='institutes.institute')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='academics.program')),
            ],
            options={
                'ordering': ['program__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institutes.institute')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.program')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('foundation', 'Foundation'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='institutes.institute')),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_topics', to='academics.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.subject')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['institute', 'is_current'], name='academics_a_institu_720fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['institute', 'start_date', 'end_date'], name='academics_a_institu_365c18_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('institute', 'name'), name='unique_academic_year_name_per_institute'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('institute',), name='unique_current_academic_year_per_institute'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['institute', 'sort_order'], name='academics_p_institu_105764_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['institute', 'category'], name='academics_p_institu_b5e2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_active'], name='academics_p_is_acti_6b6c0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_program_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['institute', 'program'], name='academics_c_institu_0ab260_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['academic_year', 'program'], name='academics_c_academi_81bb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['is_active'], name='academics_c_is_acti_941065_idx'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_cohort_code_per_institute'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('institute', 'program', 'academic_year', 'name'), name='unique_cohort_name_per_program_year'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['institute', 'program'], name='academics_s_institu_3fddd5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['institute', 'sort_order'], name='academics_s_institu_a76f83_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='academics_s_is_acti_c08ed4_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_subject_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'parent_topic'], name='academics_t_subject_950cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['institute', 'subject'], name='academics_t_institu_a5fd23_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent_topic'], name='academics_t_parent__a8fd01_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active'], name='academics_t_is_acti_7090a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('subject', 'code'), name='unique_topic_code_per_subject'),
        ),
    ]
