# Generated by Django 6.0.5 on 2026-06-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_optioncatalogentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='optioncatalogentry',
            new_name='academics_o_namespa_19c853_idx',
            old_name='academics_o_namespa_845505_idx',
        ),
        migrations.RenameIndex(
            model_name='optioncatalogentry',
            new_name='academics_o_namespa_3f2159_idx',
            old_name='academics_o_namespa_783984_idx',
        ),
        migrations.RenameIndex(
            model_name='optioncatalogentry',
            new_name='academics_o_is_defa_3adbe8_idx',
            old_name='academics_o_is_defa_866865_idx',
        ),
    ]
