# Generated by Django 6.0.5 on 2026-06-22 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


ASSESSMENT_FAMILY_SEEDS = [
    {
        "code": "school",
        "label": "School",
        "description": "Balanced academic assessment profile for school and coaching programs.",
        "sort_order": 10,
        "allowed_question_types": [
            "mcq_single",
            "mcq_multiple",
            "true_false",
            "short_answer",
            "essay_manual_review",
            "fill_in_blanks",
            "assertion_reason",
            "matrix_match",
        ],
        "scoring_defaults": {
            "strategy": "standard_marks",
            "negative_marking_default": False,
        },
        "delivery_defaults": {
            "recommended_media_flow": "guided_section_media",
            "recommended_timer_mode": "hybrid",
            "recommended_navigation_mode": "hybrid",
            "section_strategy": "structured_sections",
        },
        "analytics_preset": {
            "preset": "topic_mastery",
            "primary_lenses": ["subject", "topic", "difficulty"],
        },
        "authoring_hints": {
            "tone": "curriculum_aligned",
            "recommended_section_shape": "chapter_skill_blocks",
        },
    },
    {
        "code": "competitive",
        "label": "Competitive",
        "description": "Exam-readiness profile for competitive and entrance-style assessments.",
        "sort_order": 20,
        "allowed_question_types": [
            "mcq_single",
            "mcq_multiple",
            "integer_response",
            "numerical_response",
            "assertion_reason",
            "matrix_match",
            "comprehension_set",
        ],
        "scoring_defaults": {
            "strategy": "negative_marks",
            "negative_marking_default": True,
        },
        "delivery_defaults": {
            "recommended_media_flow": "controlled_exam_media",
            "recommended_timer_mode": "section",
            "recommended_navigation_mode": "sequential",
            "section_strategy": "timed_sections",
        },
        "analytics_preset": {
            "preset": "rank_readiness",
            "primary_lenses": ["speed", "accuracy", "skip_rate"],
        },
        "authoring_hints": {
            "tone": "exam_simulation",
            "recommended_section_shape": "timed_difficulty_mix",
        },
    },
    {
        "code": "certification",
        "label": "Certification",
        "description": "Domain-readiness profile for professional certification practice and mocks.",
        "sort_order": 30,
        "allowed_question_types": [
            "mcq_single",
            "mcq_multiple",
            "true_false",
            "short_answer",
            "comprehension_set",
        ],
        "scoring_defaults": {
            "strategy": "standard_marks",
            "negative_marking_default": False,
        },
        "delivery_defaults": {
            "recommended_media_flow": "guided_section_media",
            "recommended_timer_mode": "hybrid",
            "recommended_navigation_mode": "free_section",
            "section_strategy": "structured_sections",
        },
        "analytics_preset": {
            "preset": "domain_readiness",
            "primary_lenses": ["domain", "objective", "readiness"],
        },
        "authoring_hints": {
            "tone": "scenario_based",
            "recommended_section_shape": "domain_objective_blocks",
        },
    },
    {
        "code": "language_proficiency",
        "label": "Language Proficiency",
        "description": "Skill-block profile for reading, listening, writing, and speaking style exams.",
        "sort_order": 40,
        "allowed_question_types": [
            "mcq_single",
            "short_answer",
            "fill_in_blanks",
            "essay_manual_review",
            "comprehension_set",
        ],
        "scoring_defaults": {
            "strategy": "band_score",
            "negative_marking_default": False,
        },
        "delivery_defaults": {
            "recommended_media_flow": "controlled_exam_media",
            "recommended_timer_mode": "section",
            "recommended_navigation_mode": "sequential",
            "section_strategy": "skill_block_sections",
        },
        "analytics_preset": {
            "preset": "skill_band_progression",
            "primary_lenses": ["skill", "band", "criterion"],
        },
        "authoring_hints": {
            "tone": "skill_demonstration",
            "recommended_section_shape": "reading_listening_writing_speaking",
        },
    },
]

CATEGORY_TO_FAMILY_CODE = {
    "school": "school",
    "competitive": "competitive",
    "competition": "competitive",
    "certification": "certification",
    "professional": "certification",
    "language_proficiency": "language_proficiency",
    "language": "language_proficiency",
    "ielts": "language_proficiency",
    "toefl": "language_proficiency",
    "pte": "language_proficiency",
}


def seed_assessment_families(apps, schema_editor):
    AssessmentFamily = apps.get_model("academics", "AssessmentFamily")
    Program = apps.get_model("academics", "Program")

    created_families = {}
    for seed in ASSESSMENT_FAMILY_SEEDS:
        family, _ = AssessmentFamily.objects.update_or_create(
            code=seed["code"],
            defaults=seed,
        )
        created_families[family.code] = family

    for program in Program.objects.filter(assessment_family__isnull=True).iterator():
        category = (program.category or "").strip().lower()
        family_code = CATEGORY_TO_FAMILY_CODE.get(category)
        if family_code and family_code in created_families:
            program.assessment_family = created_families[family_code]
            program.save(update_fields=["assessment_family"])


def remove_seeded_assessment_families(apps, schema_editor):
    AssessmentFamily = apps.get_model("academics", "AssessmentFamily")
    AssessmentFamily.objects.filter(
        code__in=[seed["code"] for seed in ASSESSMENT_FAMILY_SEEDS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_seed_matrix_match_option'),
        ('institutes', '0002_institute_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('allowed_question_types', models.JSONField(blank=True, default=list)),
                ('scoring_defaults', models.JSONField(blank=True, default=dict)),
                ('delivery_defaults', models.JSONField(blank=True, default=dict)),
                ('analytics_preset', models.JSONField(blank=True, default=dict)),
                ('authoring_hints', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['code'], name='academics_a_code_c6dd15_idx'), models.Index(fields=['sort_order', 'is_active'], name='academics_a_sort_or_6fce6b_idx')],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='assessment_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academics.assessmentfamily'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['assessment_family', 'is_active'], name='academics_p_assessm_36eb52_idx'),
        ),
        migrations.RunPython(seed_assessment_families, remove_seeded_assessment_families),
    ]
