# Generated by Codex on 2026-06-25

from django.db import migrations


UPDATED_ASSESSMENT_FAMILY_CONTRACTS = {
    "school": {
        "allowed_question_types": [
            "mcq_single",
            "mcq_multiple",
            "true_false",
            "short_answer",
            "essay_manual_review",
            "fill_in_blanks",
            "assertion_reason",
            "matrix_match",
        ],
        "scoring_defaults": {
            "strategy": "standard_marks",
            "negative_marking_default": False,
            "negative_marking_scope": "disabled",
            "supports_numeric_entry": False,
            "supports_partial_scoring": True,
            "recommended_attempt_policy": "single",
        },
    },
    "competitive": {
        "allowed_question_types": [
            "mcq_single",
            "mcq_multiple",
            "true_false",
            "assertion_reason",
            "matrix_match",
            "numeric_answer",
        ],
        "scoring_defaults": {
            "strategy": "negative_marks",
            "negative_marking_default": True,
            "negative_marking_scope": "objective_only",
            "supports_numeric_entry": True,
            "supports_partial_scoring": True,
            "recommended_attempt_policy": "single",
        },
    },
    "certification": {
        "allowed_question_types": [
            "mcq_single",
            "mcq_multiple",
            "true_false",
            "short_answer",
        ],
        "scoring_defaults": {
            "strategy": "standard_marks",
            "negative_marking_default": False,
            "negative_marking_scope": "disabled",
            "supports_numeric_entry": False,
            "supports_partial_scoring": True,
            "recommended_attempt_policy": "best",
        },
    },
    "language_proficiency": {
        "allowed_question_types": [
            "mcq_single",
            "short_answer",
            "fill_in_blanks",
            "essay_manual_review",
        ],
        "scoring_defaults": {
            "strategy": "band_score",
            "negative_marking_default": False,
            "negative_marking_scope": "disabled",
            "supports_numeric_entry": False,
            "supports_partial_scoring": True,
            "recommended_attempt_policy": "single",
        },
    },
}


def refresh_assessment_family_contracts(apps, schema_editor):
    AssessmentFamily = apps.get_model("academics", "AssessmentFamily")

    for family_code, contract in UPDATED_ASSESSMENT_FAMILY_CONTRACTS.items():
        AssessmentFamily.objects.filter(code=family_code).update(
            allowed_question_types=contract["allowed_question_types"],
            scoring_defaults=contract["scoring_defaults"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_assessmentfamily_program_assessment_family_and_more"),
    ]

    operations = [
        migrations.RunPython(refresh_assessment_family_contracts, migrations.RunPython.noop),
    ]
