# Generated by Codex on 2026-07-05

from django.db import migrations


def normalize_assessment_family_codes_lowercase(apps, schema_editor):
    AssessmentFamily = apps.get_model("academics", "AssessmentFamily")

    for family in AssessmentFamily.objects.all().iterator():
        normalized_code = (family.code or "").strip().lower()
        if normalized_code and normalized_code != family.code:
            AssessmentFamily.objects.filter(pk=family.pk).update(code=normalized_code)


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_refresh_assessment_family_contracts"),
    ]

    operations = [
        migrations.RunPython(
            normalize_assessment_family_codes_lowercase,
            migrations.RunPython.noop,
        ),
    ]
