# Generated by Django 6.0.5 on 2026-05-21 05:13

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(db_index=True, editable=False, max_length=220)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='teachers/profiles/')),
                ('joined_at', models.DateField(default=datetime.date.today)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='institutes.institute')),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_role', models.CharField(choices=[('main_teacher', 'Main Teacher'), ('assistant', 'Assistant'), ('mentor', 'Mentor')], default='main_teacher', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicyear')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments', to='academics.cohort')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='institutes.institute')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'subject__name', 'teacher__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['institute', 'employee_code'], name='teachers_te_institu_721821_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['full_name'], name='teachers_te_full_na_520e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_active'], name='teachers_te_is_acti_57e8d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('institute', 'employee_code'), name='unique_teacher_employee_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['institute', 'academic_year'], name='teachers_te_institu_ee03ad_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['program', 'cohort', 'subject'], name='teachers_te_program_6db5af_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'academic_year'], name='teachers_te_teacher_259ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['is_primary'], name='teachers_te_is_prim_4551f4_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['is_active'], name='teachers_te_is_acti_ca729e_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'academic_year', 'program', 'cohort', 'subject', 'assignment_role'), name='unique_teacher_assignment_scope_role'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('institute', 'academic_year', 'program', 'cohort', 'subject'), name='unique_primary_teacher_assignment_per_scope'),
        ),
    ]
