# Generated by Django 6.0.5 on 2026-07-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_instituteonboardingrun_and_taskrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instituteonboardingrun',
            new_name='institutes__institu_749c8d_idx',
            old_name='institutes__institu_1eb390_idx',
        ),
        migrations.RenameIndex(
            model_name='instituteonboardingrun',
            new_name='institutes__profile_cfcdcb_idx',
            old_name='institutes__profile_157b61_idx',
        ),
        migrations.RenameIndex(
            model_name='instituteonboardingrun',
            new_name='institutes__status_94816a_idx',
            old_name='institutes__status_fef34d_idx',
        ),
        migrations.RenameIndex(
            model_name='instituteonboardingrun',
            new_name='institutes__source_427e47_idx',
            old_name='institutes__source_07f047_idx',
        ),
        migrations.RenameIndex(
            model_name='instituteonboardingtaskrun',
            new_name='institutes__run_id_dc8435_idx',
            old_name='institutes__run_id_c4e8f8_idx',
        ),
        migrations.RenameIndex(
            model_name='instituteonboardingtaskrun',
            new_name='institutes__task_co_b2c096_idx',
            old_name='institutes__task_co_7781f2_idx',
        ),
    ]
