# Generated by Django 6.0.5 on 2026-07-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0005_rename_institutes__institu_1eb390_idx_institutes__institu_749c8d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="management_mode",
            field=models.CharField(
                choices=[
                    ("private_institute_managed", "Private Institute Managed"),
                    ("public_institute_managed", "Public Institute Managed"),
                    ("platform_managed", "Platform Managed"),
                ],
                default="private_institute_managed",
                max_length=40,
            ),
        ),
    ]
