# Generated by Django 6.0.5 on 2026-05-21 05:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_type', models.CharField(choices=[('mcq_single', 'MCQ Single'), ('mcq_multiple', 'MCQ Multiple'), ('true_false', 'True / False'), ('short_answer', 'Short Answer')], max_length=30)),
                ('difficulty_level', models.CharField(choices=[('foundation', 'Foundation'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('default_marks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to='teachers.teacherprofile')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='institutes.institute')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='academics.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='academics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='question-bank/attachments/')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='question_bank.question')),
            ],
            options={
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('option_text', models.TextField()),
                ('option_order', models.PositiveIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.question')),
            ],
            options={
                'ordering': ['option_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='institutes.institute')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTagMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_maps', to='question_bank.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_maps', to='question_bank.questiontag')),
            ],
            options={
                'ordering': ['tag__name'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['institute', 'subject'], name='question_ba_institu_e7f170_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['program', 'topic'], name='question_ba_program_3e079a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty_level'], name='question_ba_questio_cb217e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_verified', 'is_active'], name='question_ba_is_veri_4c4194_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattachment',
            index=models.Index(fields=['question', 'attachment_type'], name='question_ba_questio_ec45ac_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattachment',
            index=models.Index(fields=['question', 'is_active'], name='question_ba_questio_7b9919_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'option_order'], name='question_ba_questio_0463b9_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'is_active'], name='question_ba_questio_64d2be_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_order'), name='unique_question_option_order'),
        ),
        migrations.AddIndex(
            model_name='questiontag',
            index=models.Index(fields=['institute', 'name'], name='question_ba_institu_994cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontag',
            index=models.Index(fields=['is_active'], name='question_ba_is_acti_234f85_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(fields=('institute', 'code'), name='unique_question_tag_code_per_institute'),
        ),
        migrations.AddIndex(
            model_name='questiontagmap',
            index=models.Index(fields=['question', 'tag'], name='question_ba_questio_8a93fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontagmap',
            constraint=models.UniqueConstraint(fields=('question', 'tag'), name='unique_question_tag_mapping'),
        ),
    ]
