# Generated by Django 6.0.5 on 2026-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionattachment',
            options={'ordering': ['display_order', 'title', 'created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='content_format',
            field=models.CharField(choices=[('plain_text', 'Plain Text'), ('markdown_latex', 'Markdown + LaTeX')], default='markdown_latex', max_length=20),
        ),
        migrations.AddField(
            model_name='questionattachment',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questionattachment',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionattachment',
            name='is_inline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='content_format',
            field=models.CharField(choices=[('plain_text', 'Plain Text'), ('markdown_latex', 'Markdown + LaTeX')], default='markdown_latex', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('diagram', 'Diagram'), ('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='questionattachment',
            index=models.Index(fields=['question', 'display_order'], name='question_ba_questio_fc7e00_idx'),
        ),
    ]
