# Generated by Django 6.0.5 on 2026-06-14 03:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_academics_o_namespa_845505_idx_academics_o_namespa_19c853_idx_and_more'),
        ('institutes', '0002_institute_metadata'),
        ('question_bank', '0002_alter_questionattachment_options_and_more'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterQuestionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='question-bank/master-attachments/')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('diagram', 'Diagram'), ('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_inline', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_format', models.CharField(choices=[('plain_text', 'Plain Text'), ('markdown_latex', 'Markdown + LaTeX')], default='markdown_latex', max_length=20)),
                ('option_text', models.TextField()),
                ('option_order', models.PositiveIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['option_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_type', models.CharField(choices=[('mcq_single', 'MCQ Single'), ('mcq_multiple', 'MCQ Multiple'), ('true_false', 'True / False'), ('short_answer', 'Short Answer')], max_length=30)),
                ('difficulty_level', models.CharField(choices=[('foundation', 'Foundation'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('content_format', models.CharField(choices=[('plain_text', 'Plain Text'), ('markdown_latex', 'Markdown + LaTeX')], default='markdown_latex', max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('default_marks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('platform', 'Platform'), ('institute', 'Institute'), ('teacher', 'Teacher')], default='institute', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared_by_request', 'Shared By Request'), ('public', 'Public')], default='private', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_questions_created', to='teachers.teacherprofile')),
                ('source_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_questions', to='institutes.institute')),
                ('source_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_questions', to='academics.program')),
                ('source_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_questions', to='academics.subject')),
                ('source_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_questions', to='academics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstituteQuestionAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('linked', 'Linked'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_question_links', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_access_links', to='institutes.institute')),
                ('linked_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_links', to='question_bank.question')),
                ('local_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_access_links', to='academics.program')),
                ('local_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_access_links', to='academics.subject')),
                ('local_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_access_links', to='academics.topic')),
                ('requested_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_question_links', to='teachers.teacherprofile')),
                ('master_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_links', to='question_bank.masterquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='master_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute_questions', to='question_bank.masterquestion'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['master_question'], name='question_ba_master__0b6bb9_idx'),
        ),
        migrations.AddField(
            model_name='masterquestionattachment',
            name='master_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='question_bank.masterquestion'),
        ),
        migrations.AddField(
            model_name='masterquestionoption',
            name='master_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.masterquestion'),
        ),
        migrations.AddIndex(
            model_name='masterquestion',
            index=models.Index(fields=['source_institute', 'source_subject'], name='question_ba_source__27d340_idx'),
        ),
        migrations.AddIndex(
            model_name='masterquestion',
            index=models.Index(fields=['source_type', 'visibility'], name='question_ba_source__7874ed_idx'),
        ),
        migrations.AddIndex(
            model_name='masterquestion',
            index=models.Index(fields=['question_type', 'difficulty_level'], name='question_ba_questio_ec2b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='masterquestion',
            index=models.Index(fields=['is_verified', 'is_active'], name='question_ba_is_veri_3b0488_idx'),
        ),
        migrations.AddIndex(
            model_name='institutequestionaccess',
            index=models.Index(fields=['institute', 'status'], name='question_ba_institu_f3cffd_idx'),
        ),
        migrations.AddIndex(
            model_name='institutequestionaccess',
            index=models.Index(fields=['master_question', 'status'], name='question_ba_master__d5d735_idx'),
        ),
        migrations.AddIndex(
            model_name='institutequestionaccess',
            index=models.Index(fields=['linked_question'], name='question_ba_linked__cfedd6_idx'),
        ),
        migrations.AddIndex(
            model_name='institutequestionaccess',
            index=models.Index(fields=['is_active'], name='question_ba_is_acti_da0c6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutequestionaccess',
            constraint=models.UniqueConstraint(fields=('institute', 'master_question'), name='unique_institute_master_question_access'),
        ),
        migrations.AddIndex(
            model_name='masterquestionattachment',
            index=models.Index(fields=['master_question', 'attachment_type'], name='question_ba_master__c0fb86_idx'),
        ),
        migrations.AddIndex(
            model_name='masterquestionattachment',
            index=models.Index(fields=['master_question', 'is_active'], name='question_ba_master__c9ca15_idx'),
        ),
        migrations.AddIndex(
            model_name='masterquestionattachment',
            index=models.Index(fields=['master_question', 'display_order'], name='question_ba_master__41ce44_idx'),
        ),
        migrations.AddIndex(
            model_name='masterquestionoption',
            index=models.Index(fields=['master_question', 'option_order'], name='question_ba_master__125a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='masterquestionoption',
            index=models.Index(fields=['master_question', 'is_active'], name='question_ba_master__20449f_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterquestionoption',
            constraint=models.UniqueConstraint(fields=('master_question', 'option_order'), name='unique_master_question_option_order'),
        ),
    ]
