# Generated by Django 6.0.5 on 2026-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_academics_o_namespa_845505_idx_academics_o_namespa_19c853_idx_and_more'),
        ('institutes', '0002_institute_metadata'),
        ('question_bank', '0003_masterquestionattachment_masterquestionoption_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['institute', 'is_active', 'subject', 'topic'], name='question_ba_institu_9559bf_idx'),
        ),
    ]
