# Generated by Django 6.0.5 on 2026-06-20 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_academics_o_namespa_845505_idx_academics_o_namespa_19c853_idx_and_more'),
        ('institutes', '0002_institute_metadata'),
        ('question_bank', '0004_question_question_ba_institu_9559bf_idx'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionPassage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('content_format', models.CharField(choices=[('plain_text', 'Plain Text'), ('markdown_latex', 'Markdown + LaTeX')], default='markdown_latex', max_length=20)),
                ('passage_text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_passages_created', to='teachers.teacherprofile')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_passages', to='institutes.institute')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_passages', to='academics.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_passages', to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_passages', to='academics.topic')),
            ],
            options={
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_bank.questionpassage'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['passage', 'passage_order'], name='question_ba_passage_36f452_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('passage__isnull', False), ('passage_order__isnull', False)), fields=('passage', 'passage_order'), name='unique_question_passage_order'),
        ),
        migrations.AddIndex(
            model_name='questionpassage',
            index=models.Index(fields=['institute', 'subject'], name='question_ba_institu_3f3560_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpassage',
            index=models.Index(fields=['institute', 'is_active', 'subject', 'topic'], name='question_ba_institu_a880e2_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpassage',
            index=models.Index(fields=['program', 'topic'], name='question_ba_program_c47d61_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpassage',
            index=models.Index(fields=['created_by_teacher', 'is_active'], name='question_ba_created_edf36e_idx'),
        ),
    ]
