from django.urls import path

from apps.economy.views import (
    AdminConfirmPaymentOrderView,
    AdminContentAccessPolicyDetailView,
    AdminContentAccessPolicyListCreateView,
    AdminEconomyCatalogItemStatusView,
    AdminEconomyCatalogOverviewView,
    AdminEconomyPolicyView,
    AdminEconomyPolicyAuditListView,
    AdminEconomyPolicyConfigView,
    AdminUnlockRuleDetailView,
    AdminUnlockRuleListCreateView,
    AdminRewardRuleDetailView,
    AdminRewardRuleListCreateView,
    AdminReferralProgramDetailView,
    AdminReferralProgramListCreateView,
    AdminSubscriptionPlanDetailView,
    AdminSubscriptionPlanListCreateView,
    AdminStarPackDetailView,
    AdminStarPackListCreateView,
    AdminGrantStarsView,
    AdminStudentPaymentOrderListView,
    AdminStudentRewardEventListView,
    AdminStudentUnlockRefreshView,
    AdminStudentWalletView,
    StudentCreateStarPackOrderView,
    StudentCreateSubscriptionOrderView,
    StudentLedgerView,
    StudentPaymentOrderListView,
    StudentRewardEventListView,
    StudentSpendStarsView,
    StudentStarPackListView,
    StudentSubscriptionListView,
    StudentSubscriptionPlanListView,
    StudentUnlockStateListView,
    StudentWalletView,
)

app_name = "economy"

urlpatterns = [
    path("wallet/", StudentWalletView.as_view(), name="student-wallet"),
    path("ledger/", StudentLedgerView.as_view(), name="student-ledger"),
    path("rewards/", StudentRewardEventListView.as_view(), name="student-rewards"),
    path("unlocks/", StudentUnlockStateListView.as_view(), name="student-unlocks"),
    path("star-packs/", StudentStarPackListView.as_view(), name="student-star-packs"),
    path("subscription-plans/", StudentSubscriptionPlanListView.as_view(), name="student-subscription-plans"),
    path("orders/", StudentPaymentOrderListView.as_view(), name="student-orders"),
    path("orders/star-pack/", StudentCreateStarPackOrderView.as_view(), name="student-create-star-pack-order"),
    path(
        "orders/subscription/",
        StudentCreateSubscriptionOrderView.as_view(),
        name="student-create-subscription-order",
    ),
    path("subscriptions/", StudentSubscriptionListView.as_view(), name="student-subscriptions"),
    path("spend-stars/", StudentSpendStarsView.as_view(), name="student-spend-stars"),
    path("admin/policy/", AdminEconomyPolicyView.as_view(), name="admin-economy-policy"),
    path("admin/policy-config/", AdminEconomyPolicyConfigView.as_view(), name="admin-economy-policy-config"),
    path("admin/policy-audit/", AdminEconomyPolicyAuditListView.as_view(), name="admin-economy-policy-audit"),
    path("admin/catalog-overview/", AdminEconomyCatalogOverviewView.as_view(), name="admin-economy-catalog-overview"),
    path("admin/star-packs/", AdminStarPackListCreateView.as_view(), name="admin-economy-star-packs"),
    path(
        "admin/star-packs/<uuid:star_pack_id>/",
        AdminStarPackDetailView.as_view(),
        name="admin-economy-star-pack-detail",
    ),
    path(
        "admin/subscription-plans/",
        AdminSubscriptionPlanListCreateView.as_view(),
        name="admin-economy-subscription-plans",
    ),
    path(
        "admin/subscription-plans/<uuid:plan_id>/",
        AdminSubscriptionPlanDetailView.as_view(),
        name="admin-economy-subscription-plan-detail",
    ),
    path(
        "admin/referral-programs/",
        AdminReferralProgramListCreateView.as_view(),
        name="admin-economy-referral-programs",
    ),
    path(
        "admin/referral-programs/<uuid:program_id>/",
        AdminReferralProgramDetailView.as_view(),
        name="admin-economy-referral-program-detail",
    ),
    path(
        "admin/reward-rules/",
        AdminRewardRuleListCreateView.as_view(),
        name="admin-economy-reward-rules",
    ),
    path(
        "admin/reward-rules/<uuid:rule_id>/",
        AdminRewardRuleDetailView.as_view(),
        name="admin-economy-reward-rule-detail",
    ),
    path(
        "admin/content-access-policies/",
        AdminContentAccessPolicyListCreateView.as_view(),
        name="admin-economy-content-access-policies",
    ),
    path(
        "admin/content-access-policies/<uuid:policy_id>/",
        AdminContentAccessPolicyDetailView.as_view(),
        name="admin-economy-content-access-policy-detail",
    ),
    path(
        "admin/unlock-rules/",
        AdminUnlockRuleListCreateView.as_view(),
        name="admin-economy-unlock-rules",
    ),
    path(
        "admin/unlock-rules/<uuid:rule_id>/",
        AdminUnlockRuleDetailView.as_view(),
        name="admin-economy-unlock-rule-detail",
    ),
    path(
        "admin/catalog-items/<str:item_type>/<uuid:item_id>/status/",
        AdminEconomyCatalogItemStatusView.as_view(),
        name="admin-economy-catalog-item-status",
    ),
    path("admin/grant-stars/", AdminGrantStarsView.as_view(), name="admin-grant-stars"),
    path(
        "admin/orders/<uuid:order_id>/confirm/",
        AdminConfirmPaymentOrderView.as_view(),
        name="admin-confirm-payment-order",
    ),
    path("admin/student/<uuid:student_id>/wallet/", AdminStudentWalletView.as_view(), name="admin-student-wallet"),
    path(
        "admin/student/<uuid:student_id>/orders/",
        AdminStudentPaymentOrderListView.as_view(),
        name="admin-student-orders",
    ),
    path(
        "admin/student/<uuid:student_id>/rewards/",
        AdminStudentRewardEventListView.as_view(),
        name="admin-student-rewards",
    ),
    path(
        "admin/student/<uuid:student_id>/refresh-unlocks/",
        AdminStudentUnlockRefreshView.as_view(),
        name="admin-student-refresh-unlocks",
    ),
]
