# Generated by Django 6.0.5 on 2026-05-21 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('exam_scheduled', 'Exam Scheduled'), ('exam_starting_soon', 'Exam Starting Soon'), ('exam_live', 'Exam Live'), ('exam_submitted', 'Exam Submitted'), ('result_published', 'Result Published'), ('teacher_review_needed', 'Teacher Review Needed'), ('question_missing_explanation', 'Question Missing Explanation')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='institutes.institute')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'is_read'], name='reports_ina_recipie_110356_idx'), models.Index(fields=['recipient_user', 'created_at'], name='reports_ina_recipie_97c75c_idx'), models.Index(fields=['notification_type', 'is_read'], name='reports_ina_notific_497ecc_idx'), models.Index(fields=['institute', 'created_at'], name='reports_ina_institu_2e2a68_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='reports_ina_related_710047_idx')],
            },
        ),
    ]
