# Generated by Django 6.0.5 on 2026-06-17 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_metadata'),
        ('reports', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inappnotification',
            name='reports_ina_recipie_110356_idx',
        ),
        migrations.RemoveIndex(
            model_name='inappnotification',
            name='reports_ina_recipie_97c75c_idx',
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient_user', 'is_active', 'is_read', 'created_at'], name='reports_ina_recipie_4f0200_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient_user', 'is_active', 'created_at'], name='reports_ina_recipie_215e78_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient_user', 'is_active', 'notification_type', 'created_at'], name='reports_ina_recipie_439845_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient_user', 'is_active', 'related_object_type', 'created_at'], name='reports_ina_recipie_25713f_idx'),
        ),
    ]
